### PR TITLE
#170695634: redesign community chat

### PR DESCRIPTION
**Pull request by alainmateso**
#### What does this PR do?
Redesign the community chat and implement demo feedback

#### Description of Task to be completed?

- Redesign the community chat to a stack of messages
- Use a single spinner across the whole app
- space the approve/reject buttons on suppliers pending requests
- Fix auto-scroll on sending message 

#### How should this be manually tested?

- Clone this branch
- run npm i
- run npm run dev
- login into the app
- navigate to the profile dropdown menu
- click on community chat
- 

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
#170695634
#### Screenshots (if appropriate)
Screen Shot 2020-01-14 at 12 30 56

#### Questions:
N/A

### CODE REVIEW

**Review by ngireric123 — CHANGES_REQUESTED** [review]
good job @alainmateso but could you add a profile picture on the chat so that your chat looks nice like on Facebook chat

**Review by sabin18 — APPROVED** [review]
great job @alainmateso

**Review by ngireric123 — APPROVED** [review]
LGTM

**Review by ceelogre — CHANGES_REQUESTED** [review]
The blue color in the message box doesn't complement the background. Look for a non-strong color.

**Review by ceelogre — APPROVED** [review]

**Pull request merged**
